CREATE INDEX IDX_TRANSACAO_EMP_DATA
ON TRANSACAO (COD_EMPRESAESTOQUE, DATAENCERRAMENTO);

CREATE INDEX IDX_TRANSACAO_ITEM_EMP_TRANS
ON TRANSACAO_ITEM (COD_EMPRESA, COD_TRANSACAO);

CREATE INDEX IDX_SAIDA_EMP_TRANS
ON SAIDA (COD_EMPRESA, COD_SAIDA);

CREATE INDEX IDX_FINLANCAMENTO_FAT
ON FINLANCAMENTO (COD_FATURATRANSACAO);

CREATE INDEX IDX_FINLANCAMENTOPARCELA_LANC
ON FINLANCAMENTOPARCELA (COD_LANCAMENTO);

CREATE INDEX IDX_FINFORMAPAGAMENTO_TIPO
ON FINFORMAPAGAMENTO (COD_FORMAPAGAMENTO, COD_FORMAPAGAMENTOTIPO);
