-- queries/vendas/debug_resumo_empresa_vendedor.sql
-- Debug de “por que está vindo vazio”
-- Parâmetros (4):
--   1) empresa (integer)
--   2) empresa (integer) repetido (regra 13/18)
--   3) dataInicio (date)
--   4) dataFim (date)

WITH P AS (
  SELECT
    CAST(? AS INTEGER) AS P_EMPRESA,
    CAST(? AS INTEGER) AS P_EMPRESA2,
    CAST(? AS DATE)    AS P_DATA_INI,
    CAST(? AS DATE)    AS P_DATA_FIM
  FROM RDB$DATABASE
),
empresas_filtradas AS (
  SELECT e.COD_EMPRESA
  FROM EMPRESA e
  WHERE e.COD_EMPRESA NOT IN (3, 5, 7, 8, 11, 12)
    AND (
      e.COD_EMPRESA = P.P_EMPRESA
      OR (
        P.P_EMPRESA2 IN (13,18)
        AND e.COD_EMPRESA IN (13,18)
      )
    )
)

SELECT '01_transacao_DATAEMISSAO' AS step, COUNT(*) AS qtd
FROM P
JOIN TRANSACAO t ON 1=1
JOIN NATUREZAOPERACAO n ON n.COD_NATUREZAOPERACAO = t.COD_NATUREZAOPERACAO
WHERE n.TIPO = 1
  AND t.DATAEMISSAO BETWEEN P.P_DATA_INI AND P.P_DATA_FIM
  AND (t.COD_EMPRESAESTOQUE IN (SELECT COD_EMPRESA FROM empresas_filtradas))

UNION ALL

SELECT '02_transacao_DATAENCERRAMENTO' AS step, COUNT(*) AS qtd
FROM P
JOIN TRANSACAO t ON 1=1
JOIN NATUREZAOPERACAO n ON n.COD_NATUREZAOPERACAO = t.COD_NATUREZAOPERACAO
WHERE n.TIPO = 1
  AND t.DATAENCERRAMENTO BETWEEN P.P_DATA_INI AND P.P_DATA_FIM
  AND (t.COD_EMPRESAESTOQUE IN (SELECT COD_EMPRESA FROM empresas_filtradas))

UNION ALL

SELECT '03_com_SAIDA' AS step, COUNT(*) AS qtd
FROM P
JOIN TRANSACAO t ON 1=1
JOIN NATUREZAOPERACAO n ON n.COD_NATUREZAOPERACAO = t.COD_NATUREZAOPERACAO
JOIN SAIDA s ON s.COD_SAIDA = t.COD_TRANSACAO AND s.COD_EMPRESA = t.COD_EMPRESA
WHERE n.TIPO = 1
  AND t.DATAEMISSAO BETWEEN P.P_DATA_INI AND P.P_DATA_FIM
  AND (t.COD_EMPRESAESTOQUE IN (SELECT COD_EMPRESA FROM empresas_filtradas))

UNION ALL

SELECT '04_com_TRANSACAO_ITEM' AS step, COUNT(*) AS qtd
FROM P
JOIN TRANSACAO t ON 1=1
JOIN NATUREZAOPERACAO n ON n.COD_NATUREZAOPERACAO = t.COD_NATUREZAOPERACAO
JOIN TRANSACAO_ITEM ti ON ti.COD_TRANSACAO = t.COD_TRANSACAO AND ti.COD_EMPRESA = t.COD_EMPRESA
WHERE n.TIPO = 1
  AND t.DATAEMISSAO BETWEEN P.P_DATA_INI AND P.P_DATA_FIM
  AND (t.COD_EMPRESAESTOQUE IN (SELECT COD_EMPRESA FROM empresas_filtradas))

UNION ALL

SELECT '05_filtrando_por_COD_EMPRESA_em_vez_de_ESTOQUE' AS step, COUNT(*) AS qtd
FROM P
JOIN TRANSACAO t ON 1=1
JOIN NATUREZAOPERACAO n ON n.COD_NATUREZAOPERACAO = t.COD_NATUREZAOPERACAO
WHERE n.TIPO = 1
  AND t.DATAEMISSAO BETWEEN P.P_DATA_INI AND P.P_DATA_FIM
  AND (t.COD_EMPRESA IN (SELECT COD_EMPRESA FROM empresas_filtradas));
