-- queries/vendas/resumo_empresa_vendedor.sql
-- Resumo por empresa e vendedor
-- DESCONTO = BRUTO - VENDIDO (SEM IPI)
-- TOTAL_CREDITOS (forma pagto tipo 6) e TOTAL_VENDIDO_SEM_CREDITOS
-- Parâmetros (4):
--   1) empresa (int)
--   2) empresa (int) repetido (regra 13/18)
--   3) dataInicio (date)
--   4) dataFim (date)

WITH
P AS (
  SELECT
    CAST(? AS INTEGER) AS P_EMPRESA,
    CAST(? AS INTEGER) AS P_EMPRESA2,
    CAST(? AS DATE)    AS P_DATA_INI,
    CAST(? AS DATE)    AS P_DATA_FIM
  FROM RDB$DATABASE
),

/* Filtra empresas válidas + regra 13/18 (aqui não existe TRANSACAO ainda) */
empresas_filtradas AS (
  SELECT e.COD_EMPRESA
  FROM EMPRESA e
  JOIN P ON 1=1
  WHERE e.COD_EMPRESA NOT IN (3, 5, 7, 8, 11, 12)
    AND (
      e.COD_EMPRESA = P.P_EMPRESA
      OR (
        P.P_EMPRESA2 IN (13, 18)
        AND e.COD_EMPRESA IN (13, 18)
      )
    )
),

tbempresa AS (
  SELECT
    e.COD_EMPRESA,
    pe.NOME AS EMPRESA,
    CASE WHEN e.COD_EMPRESA IN (13, 18) THEN 13 ELSE e.COD_EMPRESA END AS EMPRESA_COD_LOGICO,
    CASE WHEN e.COD_EMPRESA IN (13, 18) THEN 'DINIZ SUPER' ELSE pe.NOME END AS EMPRESA_NOME_LOGICO
  FROM EMPRESA e
  JOIN PESSOA pe ON pe.COD_PESSOA = e.COD_EMPRESA
  JOIN empresas_filtradas ef ON ef.COD_EMPRESA = e.COD_EMPRESA
),

/* (A) Itens: bruto, vendido, qtd transações, qtd produtos, por vendedor */
itens AS (
  SELECT
    t.COD_EMPRESAESTOQUE AS COD_EMPRESA,
    s.COD_VENDEDOR       AS COD_VENDEDOR,
    pv.NOME              AS VENDEDOR,

    COUNT(DISTINCT t.COD_TRANSACAO) AS QTD_TRANSACAO,
    SUM(ti.QUANTIDADE)              AS QTD_PRODUTOS,

    SUM(
      COALESCE(ti.VALORORIGINAL, 0)
      * COALESCE(ti.QUANTIDADE, 0)
    ) AS TOTAL_BRUTO,

    SUM(
      COALESCE(ti.TOTAL, 0)
      - COALESCE(ti.VALORDESCONTO, 0)
      - COALESCE(ti.TOTALIPI, 0)
    ) AS TOTAL_VENDIDO,

    SUM(
      (COALESCE(ti.VALORORIGINAL, 0) * COALESCE(ti.QUANTIDADE, 0))
      - (COALESCE(ti.TOTAL, 0) - COALESCE(ti.VALORDESCONTO, 0) - COALESCE(ti.TOTALIPI, 0))
    ) AS TOTAL_DESCONTO

  FROM
    P
    JOIN TRANSACAO t ON 1=1

    /* garante que só pega transações das empresas filtradas */
    JOIN tbempresa emp
      ON emp.COD_EMPRESA = t.COD_EMPRESAESTOQUE

    JOIN NATUREZAOPERACAO nat
      ON nat.COD_NATUREZAOPERACAO = t.COD_NATUREZAOPERACAO

    /* JOIN tolerante (alguns bancos usam COD_EMPRESA diferente do estoque) */
    JOIN SAIDA s
      ON s.COD_SAIDA = t.COD_TRANSACAO
     AND (
       s.COD_EMPRESA = t.COD_EMPRESAESTOQUE
       OR (t.COD_EMPRESA IS NOT NULL AND s.COD_EMPRESA = t.COD_EMPRESA)
     )

    JOIN PESSOA pv
      ON pv.COD_PESSOA = s.COD_VENDEDOR

    /* JOIN tolerante idem */
    JOIN TRANSACAO_ITEM ti
      ON ti.COD_TRANSACAO = t.COD_TRANSACAO
     AND (
       ti.COD_EMPRESA = t.COD_EMPRESAESTOQUE
       OR (t.COD_EMPRESA IS NOT NULL AND ti.COD_EMPRESA = t.COD_EMPRESA)
     )

  WHERE
    nat.TIPO = 1
    AND t.DATAENCERRAMENTO BETWEEN P.P_DATA_INI AND P.P_DATA_FIM

  GROUP BY
    t.COD_EMPRESAESTOQUE,
    s.COD_VENDEDOR,
    pv.NOME
),

/* (B) Financeiro: total pago em CREDITOS por vendedor */
creditos AS (
  SELECT
    t.COD_EMPRESAESTOQUE AS COD_EMPRESA,
    s.COD_VENDEDOR       AS COD_VENDEDOR,

    SUM(
      COALESCE(
        IIF(flp.DATAPAGAMENTO IS NULL, flp.VALOR, flp.VALORPAGO),
        0
      )
    ) AS TOTAL_CREDITOS

  FROM
    P
    JOIN TRANSACAO t ON 1=1

    JOIN tbempresa emp
      ON emp.COD_EMPRESA = t.COD_EMPRESAESTOQUE

    JOIN NATUREZAOPERACAO nat
      ON nat.COD_NATUREZAOPERACAO = t.COD_NATUREZAOPERACAO

    JOIN SAIDA s
      ON s.COD_SAIDA = t.COD_TRANSACAO
     AND (
       s.COD_EMPRESA = t.COD_EMPRESAESTOQUE
       OR (t.COD_EMPRESA IS NOT NULL AND s.COD_EMPRESA = t.COD_EMPRESA)
     )

    JOIN FINFATURATRANSACAO fft
      ON fft.COD_FATURATRANSACAO = t.COD_FATURATRANSACAO

    JOIN FINLANCAMENTO fl
      ON fl.COD_FATURATRANSACAO = fft.COD_FATURATRANSACAO

    JOIN FINLANCAMENTOPARCELA flp
      ON flp.COD_LANCAMENTO = fl.COD_LANCAMENTO

    JOIN FINFORMAPAGAMENTO ffp
      ON ffp.COD_FORMAPAGAMENTO = flp.COD_FORMAPAGAMENTO

  WHERE
    nat.TIPO = 1
    AND t.DATAEMISSAO BETWEEN P.P_DATA_INI AND P.P_DATA_FIM
    AND ffp.COD_FORMAPAGAMENTOTIPO = 6  -- CREDITOS

  GROUP BY
    t.COD_EMPRESAESTOQUE,
    s.COD_VENDEDOR
)

SELECT
  emp.COD_EMPRESA,
  emp.EMPRESA,
  emp.EMPRESA_COD_LOGICO,
  emp.EMPRESA_NOME_LOGICO,

  i.COD_VENDEDOR,
  i.VENDEDOR,

  i.QTD_TRANSACAO,
  i.QTD_PRODUTOS,

  i.TOTAL_BRUTO,
  i.TOTAL_VENDIDO,

  i.TOTAL_DESCONTO AS TOTAL_DESCONTO,

  CASE
    WHEN i.TOTAL_BRUTO = 0 THEN 0
    ELSE (i.TOTAL_DESCONTO / NULLIF(i.TOTAL_BRUTO, 0)) * 100
  END AS PERC_DESCONTO,

  COALESCE(c.TOTAL_CREDITOS, 0) AS TOTAL_CREDITOS,

  (i.TOTAL_VENDIDO - COALESCE(c.TOTAL_CREDITOS, 0)) AS TOTAL_VENDIDO_SEM_CREDITOS

FROM
  itens i
  JOIN tbempresa emp
    ON emp.COD_EMPRESA = i.COD_EMPRESA
  LEFT JOIN creditos c
    ON c.COD_EMPRESA = i.COD_EMPRESA
   AND c.COD_VENDEDOR = i.COD_VENDEDOR

ORDER BY
  emp.EMPRESA_COD_LOGICO,
  i.VENDEDOR;
