-- Analise de estoque consolidada com ação sugerida
-- Baseado na documentação oficial do módulo ESTOQUE.md

SELECT
    e.COD_EMPRESA,
    pesEmp.NOME AS EMPRESA,

    e.COD_PRODUTO           AS COD_ITEM,
    e.DESCRICAO_PRODUTO     AS DESCRICAO_ITEM,

    e.SALDO,
    e.CAF,
    e.ULTIMA_ENTRADA,

    /* DIAS EM ESTOQUE */
    CASE 
        WHEN e.ULTIMA_ENTRADA IS NULL THEN NULL
        ELSE CURRENT_DATE - e.ULTIMA_ENTRADA
    END AS DIAS_ESTOQUE,

    /* AÇÃO SUGERIDA CONFORME DOCUMENTAÇÃO */
    CASE
        WHEN e.SALDO <= 0 THEN 'SEM ESTOQUE'
        WHEN e.ULTIMA_ENTRADA IS NULL THEN 'ANALISAR COMPRA'
        WHEN (CURRENT_DATE - e.ULTIMA_ENTRADA) <= 60 THEN 'OK'
        WHEN (CURRENT_DATE - e.ULTIMA_ENTRADA) BETWEEN 61 AND 120 THEN 'ANALISAR COMPRA'
        ELSE 'LIQUIDAR 30%'
    END AS ACAO_SUGERIDA,

    /* FORNECEDOR PRINCIPAL */
    e.COD_FORNECEDOR,
    pforn.NOME AS NOME_FORNECEDOR

FROM
    VW_ESTOQUE_ANALITICO e
    JOIN PESSOA pesEmp ON pesEmp.COD_PESSOA = e.COD_EMPRESA
    LEFT JOIN PESSOA pforn ON pforn.COD_PESSOA = e.COD_FORNECEDOR

WHERE
    e.COD_EMPRESA = CAST(? AS INTEGER)

ORDER BY
    pesEmp.NOME,
    NOME_FORNECEDOR,
    DESCRICAO_ITEM;
